### PR TITLE
Speed up algorithm

### PR DESCRIPTION
**Pull request by kikill95**
Firstly, we sort `left` and `right` parts, so we can do less operations, because on `leftPair < rightPair` we can skip this element. The second thing for speed up was using `rightIndex`, because after sorting we can skip first part of `right` before `rightIndex`

### CODE REVIEW

**Comment by wooorm** [comment]
This looks very solid! Did you run benchmark tests to make sure it increases the speed?

**Comment by kikill95** [comment]
Yes, I did
Will send them in comments later

**Comment by kikill95** [comment]
So, I did benchmark tests in vacuum and they are slower than previous solution. Also, in my project we "preprocess" data, so this works faster than existed. I will close PR for now and if "optimized" solution in vacuum will be faster, I will open it again. Anyway, I will continue to work with it

**Comment by wooorm** [comment]
Oh how interesting! Maybe this starts being useful on bigger input values? 🤔

**Pull request closed without merging**
