### PR TITLE
Fix bug where comparing two single character values returns NaN

### PR DESCRIPTION
**Pull request by bameyrick**
This is potentially more of a problem with the `n-gram/bigram` dependency, but I noticed when one or both of the values to compare are just single characters the left and right arrays remain empty, causing the algorithm to return `NaN`.

I've added a check for this where it will just create the left/right array with the value in if the length of the value is 1.

### CODE REVIEW

**Comment by wooorm** [comment]
@bameyrick Nice, thank you!

* Could you remove the package lock?
* For the future, could you split different changes into different PRs? It’s fine for now, but the new keywords don’t have anything to do with the code changes

**Comment by bameyrick** [comment]
@wooorm No problem, that's removed now.
Noted, will split PRs in future 👍

**Comment by bameyrick** [comment]
@wooorm Is this good to merge now?

**Comment by wooorm** [comment]
@bameyrick Yes 😉

**Pull request merged**
